In [ ]:
!pip install numpy
!pip install pandas

In [39]:
import numpy as np
import pandas as pd 

In [40]:
df = pd.read_csv("D:\ML\HealthRiskPrediction\synthetic_health_data.csv")

In [42]:
df.sample(5)

age     diet  exercise_days  sleep_hours  stress   bmi smoking alcohol  \
3932   53  Average              2            7     Low  38.0     Yes     Low   
1488   47  Average              2            7  Medium  27.9      No     Low   
1722   45     Poor              4            8    High  19.1      No    High   
1430   31  Average              1            6  Medium  17.1      No    High   
2142   24  Average              5            3     Low  25.2      No     Low   

     family_history risk_level  
3932             No     Medium  
1488            Yes        Low  
1722            Yes     Medium  
1430             No        Low  
2142            Yes        Low

In [4]:
df.shape

(4000, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             4000 non-null   int64  
 1   diet            4000 non-null   object 
 2   exercise_days   4000 non-null   int64  
 3   sleep_hours     4000 non-null   int64  
 4   stress          4000 non-null   object 
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object 
 7   alcohol         4000 non-null   object 
 8   family_history  4000 non-null   object 
 9   risk_level      4000 non-null   object 
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB


In [6]:
df.isnull().sum()

age               0
diet              0
exercise_days     0
sleep_hours       0
stress            0
bmi               0
smoking           0
alcohol           0
family_history    0
risk_level        0
dtype: int64

In [43]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head()

age     diet  exercise_days  sleep_hours  stress   bmi smoking alcohol  \
0   56     Poor              3            4    High  19.9      No    High   
1   69  Average              2            5    High  33.9      No     Low   
2   46  Average              7           12  Medium  31.0     Yes     Low   
3   32     Good              1           11    High  38.1      No    High   
4   60     Good              6           11     Low  34.6      No     Low   

  family_history risk_level  
0            Yes       High  
1            Yes       High  
2            Yes     Medium  
3             No     Medium  
4            Yes     Medium

In [9]:
# numerical data --> age, bmi, exercise_days, sleep_hours 
# categorical data --> diet, stress, smoking, alcohol, family_history
# target data --> risk_level

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             4000 non-null   int64  
 1   diet            4000 non-null   object 
 2   exercise_days   4000 non-null   int64  
 3   sleep_hours     4000 non-null   int64  
 4   stress          4000 non-null   object 
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object 
 7   alcohol         4000 non-null   object 
 8   family_history  4000 non-null   object 
 9   risk_level      4000 non-null   object 
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB


In [11]:
# analyse age column
print(df['age'].max())
print(df['age'].min())

80
18


In [12]:
# analyse diet column
df['diet'].value_counts()

diet
Average    1987
Poor       1216
Good        797
Name: count, dtype: int64

In [13]:
# analyse excersice_days column
print(df['exercise_days'].max())
print(df['exercise_days'].min())

7
0


In [14]:
# analyse sleep_hours column
print(df['sleep_hours'].min())
print(df['sleep_hours'].max())

3
12


In [15]:
# analyse stress column
print(df['stress'].value_counts())

stress
Medium    1940
Low       1239
High       821
Name: count, dtype: int64


In [49]:
from sklearn.model_selection import train_test_split

X = df.drop("risk_level", axis=1)   # drop target column from dataset
y = df["risk_level"]                # Target value

# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.head()

age     diet  exercise_days  sleep_hours  stress   bmi smoking alcohol  \
3994   38  Average              4            7    High  36.4     Yes    High   
423    21     Poor              1            8     Low  35.3      No     Low   
2991   32  Average              0            6  Medium  17.4      No  Medium   
1221   32  Average              2           12  Medium  24.4     Yes     Low   
506    67     Poor              3            7    High  17.9      No     Low   

     family_history  
3994             No  
423             Yes  
2991             No  
1221             No  
506              No

In [17]:
# from sklearn.preprocessing import OrdinalEncoder

# # Example column
# X_train["diet"].value_counts()


In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

# # encoding of single column
# oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"]])
# # Fit on train
# X_train[["diet"]] = oe.fit_transform(X_train[["diet"]])

# # Transform test
# X_test[["diet"]] = oe.transform(X_test[["diet"]])

# X_train

In [18]:
ordinal_cols = ["diet", "stress", "alcohol"]
print(df["diet"].value_counts())
print(df["stress"].value_counts())
print(df["alcohol"].value_counts())

for col in ordinal_cols:
    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)


diet
Average    1987
Poor       1216
Good        797
Name: count, dtype: int64
stress
Medium    1940
Low       1239
High       821
Name: count, dtype: int64
alcohol
Low       2004
Medium    1220
High       776
Name: count, dtype: int64


In [19]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_cols = ["diet", "stress", "alcohol"]
category_orders = [
    ["Poor", "Average", "Good"],    # diet
    ["Low", "Medium", "High"],      # stress
    ["Low", "Medium", "High"]       # alcohol
]

oe = OrdinalEncoder(categories=category_orders)

X_train[ordinal_cols] = oe.fit_transform(X_train[ordinal_cols])
X_test[ordinal_cols] = oe.transform(X_test[ordinal_cols])


In [51]:
X_train

age     diet  exercise_days  sleep_hours  stress   bmi smoking alcohol  \
3994   38  Average              4            7    High  36.4     Yes    High   
423    21     Poor              1            8     Low  35.3      No     Low   
2991   32  Average              0            6  Medium  17.4      No  Medium   
1221   32  Average              2           12  Medium  24.4     Yes     Low   
506    67     Poor              3            7    High  17.9      No     Low   
...   ...      ...            ...          ...     ...   ...     ...     ...   
1130   46  Average              6            7  Medium  28.2      No     Low   
1294   43  Average              5            4  Medium  39.8      No     Low   
860    22  Average              7           10     Low  23.4      No     Low   
3507   50  Average              7            9     Low  31.5      No     Low   
3174   25  Average              4            7  Medium  30.0      No     Low   

     family_history  
3994             No  
423             Yes  
2991             No  
1221             No  
506              No  
...             ...  
1130             No  
1294             No  
860              No  
3507            Yes  
3174             No  

[3200 rows x 9 columns]

In [27]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe_cols = ["smoking", "family_history"]
ohe = OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore")

# Fit on train, transform both
train_encoded = ohe.fit_transform(X_train[ohe_cols])
test_encoded = ohe.transform(X_test[ohe_cols])

# Convert to DataFrame with new column names
ohe_train_df = pd.DataFrame(train_encoded, 
                            columns=ohe.get_feature_names_out(ohe_cols),
                            index=X_train.index)

ohe_test_df = pd.DataFrame(test_encoded, 
                           columns=ohe.get_feature_names_out(ohe_cols),
                           index=X_test.index)

# Drop original categorical columns and join new encoded ones
X_train = X_train.drop(columns=ohe_cols).join(ohe_train_df)
X_test = X_test.drop(columns=ohe_cols).join(ohe_test_df)


In [28]:
X_train

age  diet  exercise_days  sleep_hours  stress   bmi  alcohol  \
3994   38   1.0              4            7     2.0  36.4      2.0   
423    21   0.0              1            8     0.0  35.3      0.0   
2991   32   1.0              0            6     1.0  17.4      1.0   
1221   32   1.0              2           12     1.0  24.4      0.0   
506    67   0.0              3            7     2.0  17.9      0.0   
...   ...   ...            ...          ...     ...   ...      ...   
1130   46   1.0              6            7     1.0  28.2      0.0   
1294   43   1.0              5            4     1.0  39.8      0.0   
860    22   1.0              7           10     0.0  23.4      0.0   
3507   50   1.0              7            9     0.0  31.5      0.0   
3174   25   1.0              4            7     1.0  30.0      0.0   

      smoking_Yes  family_history_Yes  
3994          1.0                 0.0  
423           0.0                 1.0  
2991          0.0                 0.0  
1221          1.0                 0.0  
506           0.0                 0.0  
...           ...                 ...  
1130          0.0                 0.0  
1294          0.0                 0.0  
860           0.0                 0.0  
3507          0.0                 1.0  
3174          0.0                 0.0  

[3200 rows x 9 columns]

In [ ]:
# ordinal --> diet, stress, alcohol
# ohe --> smoking, family_history
# numerical --> age, sleep_hours, bmi, exercise_days

In [34]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Select numeric columns you want to scale
num_cols = ["age", "diet", "exercise_days", "bmi", "sleep_hours", "stress", "alcohol"]

scaler = StandardScaler()

# Fit on train, transform train
scaled_train = scaler.fit_transform(X_train[num_cols])
scaled_train_df = pd.DataFrame(scaled_train, columns=num_cols, index=X_train.index)

# Transform test (important: only transform, not fit again)
scaled_test = scaler.transform(X_test[num_cols])
scaled_test_df = pd.DataFrame(scaled_test, columns=num_cols, index=X_test.index)

print(scaled_train_df.head())
print(scaled_test_df.head())


           age      diet  exercise_days       bmi  sleep_hours    stress  \
3994 -0.613789  0.141776       0.222678  1.208572    -0.194733  1.549394   
423  -1.552214 -1.275986      -1.069772  1.055616     0.156533 -1.260501   
2991 -0.944997  0.141776      -1.500589 -1.433400    -0.545999  0.144446   
1221 -0.944997  0.141776      -0.638955 -0.460042     1.561596  0.144446   
506   0.987054 -1.275986      -0.208138 -1.363875    -0.194733  1.549394   

       alcohol  
3994  1.707436  
423  -0.891277  
2991  0.408079  
1221 -0.891277  
506  -0.891277  
           age      diet  exercise_days       bmi  sleep_hours    stress  \
555   1.704673  0.141776       1.515129  1.083426     0.859064 -1.260501   
3491  0.324636  0.141776      -0.638955  1.695251    -1.248530  0.144446   
527   1.263061  0.141776      -0.208138  1.695251     0.859064  0.144446   
3925  0.655845  0.141776      -1.069772 -1.586357     1.561596 -1.260501   
2989  1.152658  1.559539      -0.638955 -0.515663     0.50779

In [ ]:
# import pandas as pd
# from sklearn.preprocessing import StandardScaler

# # Example data
# df = pd.DataFrame({"bmi": df["bmi"]})

# scaler = StandardScaler()

# # Fit & transform
# df["bmi_scaled"] = scaler.fit_transform(df[["bmi"]])

# print(df)

       bmi  bmi_scaled
0     19.9   -1.091075
1     33.9    0.857211
2     31.0    0.453638
3     38.1    1.441697
4     34.6    0.954626
...    ...         ...
3995  16.6   -1.550314
3996  38.8    1.539112
3997  30.3    0.356223
3998  35.0    1.010291
3999  25.2   -0.353510

[4000 rows x 2 columns]


In [36]:
num_cols = ["age", "diet", "exercise_days", "bmi", "sleep_hours", "stress", "alcohol"]

# 1. Drop the numeric columns from original train/test
X_train_rest = X_train.drop(columns=num_cols)
X_test_rest  = X_test.drop(columns=num_cols)

# 2. Merge scaled numeric df with the remaining columns
X_train_final = pd.concat([X_train_rest, scaled_train_df], axis=1)
X_test_final  = pd.concat([X_test_rest, scaled_test_df], axis=1)

print(X_train_final.head())
print(X_test_final.head())

      smoking_Yes  family_history_Yes       age      diet  exercise_days  \
3994          1.0                 0.0 -0.613789  0.141776       0.222678   
423           0.0                 1.0 -1.552214 -1.275986      -1.069772   
2991          0.0                 0.0 -0.944997  0.141776      -1.500589   
1221          1.0                 0.0 -0.944997  0.141776      -0.638955   
506           0.0                 0.0  0.987054 -1.275986      -0.208138   

           bmi  sleep_hours    stress   alcohol  
3994  1.208572    -0.194733  1.549394  1.707436  
423   1.055616     0.156533 -1.260501 -0.891277  
2991 -1.433400    -0.545999  0.144446  0.408079  
1221 -0.460042     1.561596  0.144446 -0.891277  
506  -1.363875    -0.194733  1.549394 -0.891277  
      smoking_Yes  family_history_Yes       age      diet  exercise_days  \
555           1.0                 1.0  1.704673  0.141776       1.515129   
3491          0.0                 1.0  0.324636  0.141776      -0.638955   
527           0

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Initialize the model
log_reg = LogisticRegression(max_iter=1000, random_state=42)

# 2. Train (fit) the model on training data
log_reg.fit(X_train_final, y_train)

# 3. Predict on test data
y_pred = log_reg.predict(X_test_final)

# 4. Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.845

Confusion Matrix:
 [[ 15   0   9]
 [  0 253  58]
 [  3  54 408]]

Classification Report:
               precision    recall  f1-score   support

        High       0.83      0.62      0.71        24
         Low       0.82      0.81      0.82       311
      Medium       0.86      0.88      0.87       465

    accuracy                           0.84       800
   macro avg       0.84      0.77      0.80       800
weighted avg       0.84      0.84      0.84       800

